# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 641b892dce8409e1c78e917b3729dfff0b8cf4d221311841e03358b80f5d3ee6c14cad34a334f76fdd3752d6b58f097f2769c32dd1bc32400fcf833b763ebde6

test:
  secret_key_base: 82ad85c919f322b7a077ee03c3a5dd292716f29fdf751071ea17f840ea5fa5eb2657c96c2240fda00cc8ffde257f7884ef508c12f3a1f46191b3a894a816a0e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
